# Sidebar navigation

- label: '总体介绍'
  link: '/'
- label: '使用教材介绍'
  link: '/book'
- label: 'Julia 软件安装'
  link: '/getting-started'  
- label: 微积分
  items:
    - label: 'Creating docs'
      link: '/usage/creating-docs'
    - label: 'Navigation'
      link: '/usage/navigation'
    - label: 'Shadowing'
      link: '/usage/shadowing'
    - label: 'Using YAML files'
      link: '/usage/using-yaml-files'
- label: 资源
  items:
    - label: '矩阵分解方法资源'
      link : '/resource/matrix-decomposition'
- label: 概率与统计
  items:
     - label: '序言'
       link: '/stat/preface'




    