# Sidebar navigation

- label: '总体介绍'
  link: '/'
- label: '使用教材介绍'
  link: '/book'
- label: 'Julia 软件安装'
  link: '/getting-started'  
- label: 微积分
  items:
    - label: '微积分序言'
      link: '/calculus/perface'
    - label: '第一个函数图像'
      link: '/calculus/What is Function'
    - label: 'ch01'
      link: '/calculus/ch01'
    - label: 'ch02'
      link: '/calculus/ch02'
    - label: 'ch03'
      link: '/calculus/ch03'
    - label: 'ch04'
      link: '/calculus/ch04'
    - label: 'ch05'
      link: '/calculus/ch05'
    - label: 'ch06'
      link: '/calculus/ch06'
    - label: 'ch07'
      link: '/calculus/ch07'
    - label: 'ch08'
      link: '/calculus/ch08'
    - label: 'ch09'
      link: '/calculus/ch09'
    - label: 'ch10'
      link: '/calculus/ch10'
    - label: 'ch11'
      link: '/calculus/ch11'
     
- label: 线性代数
  items:
    - label: '线性代数序言'
      link: '/linearalgebra/perface'
- label: 资源
  items:
    - label: '矩阵分解方法资源'
      link : '/resource/matrix-decomposition'
- label: 概率与统计
  items:
     - label: '序言'
       link: '/stat/preface'




    